version: '3'
services:
  webz-001:
    image: webz-001-image
    build: ./webz-001
    container_name: webz-001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock ### Needed for container to use docker commands 
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN

  webz-002:
    image: webz-common-image
    build: ./webz-common
    container_name: webz-002
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock ### Needed for container to use docker commands 

  webz-003:
    image: webz-common-image
    build: ./webz-common
    container_name: webz-003
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock ### Needed for container to use docker commands 

  webz-004:
    image: webz-004-image
    build: ./webz-004
    container_name: webz-004
    stdin_open: true
    tty: true
    ports:
      - "8080:8080" ### Share localhost:8080 to host (Jenkins)
    volumes:
      - ./jenkins_home:/var/jenkins_home ### Save jenkins settings on host to avoid re-configuring every build
      - ./jenkins_log:/var/log/jenkins ### Provide access to jenkins_log from host
